export const SAVE_CODE = 'SAVE_CODE'
export const SAVE_CODE_SUCCESS = 'SAVE_CODE_SUCCESS'
export const SAVE_CODE_FAILURE = 'SAVE_CODE_FAILURE'

export const GET_CODE = 'GET_CODE'
export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS'
export const GET_CODE_FAILURE = 'GET_CODE_FAILURE'